### ISSUE TITLE
команда "двери" с автосписком известных закрытых дверей

### ISSUE THREAD

**Issue by Oreolek** [fireton/mp-newlib#1]
В поджанре "особняк с закрытыми комнатами" закрытые двери - это как список нерешённых квестов: ты нашёл закрытую дверь, ушёл в другой угол мира, нашёл ключ и забыл уже от чего он. Поэтому очень удобным будет модуль команды `двери` или `замки`, который выводит список из уже известных (комнаты посещены), но ещё не открытых дверей.

Такое в принципе удобно для всех закрытых контейнеров, замков и прочего, но с контейнерами больше вопросов и они могут быть переносимыми, а вот двери - это попроще.

**Comment by Oreolek** [comment]
Удивительно просто делается:

```
Verb {
   "#doors",
   "двери",
   "Doors"
}

function mp:Doors()
  local doors = std.list {};
  std.for_each_obj(function(v)
    -- посещённые комнаты
    if (v and v:type 'room' and visited(v)) then
      v.obj:for_each(function(d)
        if (d and d:has('locked')) then
          doors:add(d.nam)
        end
      end)
    end
  end)
  if (#doors == 0) then
    p("Пока что вы не встречали запертых дверей.");
  else
    pn('В комнатах, которые вы посещали, всё ещё закрыты:')
    doors:for_each(function(v)
      p(' '..where(v).title)
      p(' - ')
      pn(_(v):noun('им'))
    end)
  end
end
```

**Comment by fireton** [comment]
Не вижу, зачем это делать фичей библиотеки. По-моему, это кастомная фича конкретной игры. Можно оформить как модуль например.
